src/main/java/br/com/dog/trainer/model/Cachorro.java
package br.com.dog.trainer.model;

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

@Entity
public class Cachorro {
	@Id @GeneratedValue
	private Long id;
	
	private String nome;
	private String apelido;
	private Date dataNascimento;
	
	@ManyToOne
	private Raca raca;
	
	@OneToOne
	private Adestrador adestrador;
	
	@OneToOne
	private Proprietario proprietario;
	
	public Long getId() {
		return id;
	}
	
	public void setId(Long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}
	
	public void setNome(String nome) {
		this.nome = nome;
	}
	
	public Date getDataNascimento() {
		return dataNascimento;
	}
	
	public void setDataNascimento(Date dataNascimento) {
		
		this.dataNascimento = dataNascimento;
	}
	
	public Raca getRaca() {
		return raca;
	}

	public void setRaca(Raca raca) {
		this.raca = raca;
	}

	public String getApelido() {
		return apelido;
	}

	public void setApelido(String apelido) {
		this.apelido = apelido;
	}

	public Adestrador getAdestrador() {
		return adestrador;
	}

	public void setAdestrador(Adestrador adestrador) {
		this.adestrador = adestrador;
	}

	public Proprietario getProprietario() {
		return proprietario;
	}

	public void setProprietario(Proprietario proprietario) {
		this.proprietario = proprietario;
	}
	
	public String getDataFormatada(){
		SimpleDateFormat dt = new SimpleDateFormat("dd/mm/yyyy");
		
		return dt.format(dataNascimento);
	}
}

src/main/java/br/com/dog/trainer/controller/CachorroController.java
package br.com.dog.trainer.controller;

import javax.inject.Inject;

import br.com.caelum.vraptor.Controller;
import br.com.caelum.vraptor.Delete;
import br.com.caelum.vraptor.Get;
import br.com.caelum.vraptor.Path;
import br.com.caelum.vraptor.Post;
import br.com.caelum.vraptor.Put;
import br.com.dog.trainer.dao.CachorroDao;
import br.com.dog.trainer.dao.ProprietarioDao;
import br.com.dog.trainer.dao.RacaDao;
import br.com.dog.trainer.model.Cachorro;

@Controller
public class CachorroController extends BaseController{

	@Inject private RacaDao racaDao;
	@Inject private ProprietarioDao proprietarioDao;
	@Inject private CachorroDao cachorroDao;
	

	
	@Path("/cachorro/formCachorro")
	public void formCachorro() {
		result.include("racaCachorroList", racaDao.buscarTodos());
		result.include("proprietarioList", proprietarioDao.buscarTodosDoAdestrador(getIdAdestrador()));
	}

	@Path("/listarCachorros")
	public void listarCachorros() {
		System.out.println(">>>>>>>>>>>>>>getIdAdestrador "+getIdAdestrador());
		
		result.include("cachorros",cachorroDao.buscarTodosDoAdestrador(getIdAdestrador()));
	}
	
	@Get("/cachorro/verCachorro/{cachorro.id}")
	public Cachorro verCachorro(Cachorro cachorro) {
		return cachorroDao.buscarPorId(cachorro.getId());
	}

	@Post("/cachorro")
	public void insert(Cachorro cachorro) {
		this.setAdestrador(cachorro);
		cachorroDao.inserir(cachorro);
		result.redirectTo(this).verCachorro(cachorro);
	}
	@Get("/cachorro/editarCachorro/{cachorro.id}")
	public Cachorro editarCachorro(Cachorro cachorro){
		
		result.include("racaCachorroList", racaDao.buscarTodos());
		result.include("proprietarioList", proprietarioDao.buscarTodosDoAdestrador(getIdAdestrador()));
		
		return cachorroDao.buscarPorId(cachorro.getId());
	}
	
	@Put("/cachorro")
	public void update(Cachorro cachorro) {
		this.setAdestrador(cachorro);
		cachorroDao.alterar(cachorro);
		result.redirectTo(this).verCachorro(cachorro);
	}
	
	@Delete("/cachorro/{cachorro.id}")
	public void remove(Cachorro cachorro) {
		cachorroDao.excluir(cachorro);
		result.redirectTo(this).listarCachorros();
	}
	
	private void setAdestrador(Cachorro cachorro) {
		adestrador.setId(getIdAdestrador());
		cachorro.setAdestrador(adestrador);
	}

}

src/main/webapp/WEB-INF/jsp/cachorro/editarCachorro.jsp
<%@include file="formCachorro.jsp"%>

src/main/webapp/WEB-INF/jsp/cachorro/listarCachorros.jsp
<h3 class="ls-title-intro"> 
	<fmt:message key="label.menu.cachorros" />
 </h3>
	
	
<form action="<c:url value='/cachorro/formCachorro'/>" id="incluir" class="ls-form ls-form-horizontal row " data-ls-module="form" method="post">
	<button type="submit" class="ls-btn-primary btnIncluir">
		<i class="fa fa-plus-circle"></i>
	</button>
</form>

<table class="ls-table ls-table-striped">
  <thead>
    <tr>
      <th><fmt:message key="label.nome"/></th>
      <th><fmt:message key="label.raca"/></th>
      <th><fmt:message key="label.proprietario"/></th>
       <th> <fmt:message key="label.padrao.acao"/></th>
    </tr>
  </thead>
  <tbody>
  
  	<c:forEach items="${cachorros}" var="cachorro">

		<tr>
			<td>${cachorro.nome}</td>
			<td>${cachorro.raca.descricao}</td>
			<td>${cachorro.proprietario.nome}</td>
			<td>
				<form action="<c:url value='/cachorro/${cachorro.id }'/>" method="POST">
					<a href="<c:url value='/cachorro/verCachorro/${cachorro.id }'/>" class="ls-btn btnVer">
						<i class="fa fa-eye"></i>
					</a>
				
					<a href="<c:url value='/cachorro/editarCachorro/${cachorro.id }'/>" class="ls-btn btnEditar">
						<i class="fa fa-edit"></i>
					</a>
					<button type="submit" onclick="return confirm('Deseja realmente remover?');"
							class="ls-btn-danger btnExcluir">
						<i class="fa fa-trash"></i>
					</button> 
					<input type="hidden" name="_method" value="DELETE">
				</form>
			</td>
		</tr>

	</c:forEach>
</table>

<script>
	$(document).ready(function() {

		$("#incluir").click(function() {
			$("form").submit();

		});

	});
</script>

src/main/webapp/WEB-INF/jsp/cachorro/verCachorro.jsp
<h1 class="ls-title-intro">
	<fmt:message key="label.menu.cachorros"/> 
</h1>
<form action="<c:url value='/cachorro/${cachorro.id }'/>" class="ls-form ls-form-horizontal row " data-ls-module="form" method="post">

	<a href="<c:url value="/listarCachorros"/>" class="ls-btn btnVoltar">
		<i class="fa fa-reply"></i> 
	</a>
	
	<a href="<c:url value="/cachorro/editarCachorro/${cachorro.id}"/>" class="ls-btn btnEditar">
		<i class="fa fa-edit"></i> 
	</a>
	
	<button type="submit" onclick="return confirm('Deseja realmente remover esse projeto?');"
			class="ls-btn ls-btn-danger btnExcluir">
		<i class="fa fa-trash"></i>
	</button> 
	<input type="hidden" name="_method" value="DELETE">
	
</form>
<p>

<div class="ls-box">
 	
 	<label class="ls-label col-md-6 col-lg-8">
 		<span>
        <b class="ls-label-text" ><fmt:message key="label.nome"/>:</b>
	      	${cachorro.nome} 
      	</span>
      </label>
 	<label class="ls-label col-md-6 col-lg-8">
 		<span>
        <b class="ls-label-text"><fmt:message key="label.idade"/>:</b>
	      	${cachorro.dataFormatada}
      	</span>
      </label>
   	<label class="ls-label col-md-6 col-lg-8">
 		<span>
        <b class="ls-label-text"><fmt:message key="label.raca"/>:</b>
	      	${cachorro.raca.descricao}
      	</span>
      </label>
   	<label class="ls-label col-md-6 col-lg-8">
 		<span>
        <b class="ls-label-text"><fmt:message key="label.proprietario"/>:</b>
	      	${cachorro.proprietario.nome}
      	</span>
      </label>
 </div>